#%RAML 1.0
title: Game Title API

types:
  Title: !include exchange_modules/57f0dd2e-7c19-43c0-bdb3-31bcb6cd3037/title-data-type/1.0.2/title-data-type.raml


/update:
  description: Update title
  displayName: Update title
  post:
    body:
      application/json:
        type: Title
    responses:
        201:
          body:
            application/json:
              type: any

/create:
  description: Create title
  displayName: Create title
  post:
    body:
      application/json:
        type: Title
    responses:
        201:
          body:
            application/json:
              type: any

/retrieve:
  description: Retrieve titles
  displayName: Retrieve titles
  get:
    responses:
        200:
          body:
            application/json:
              type: any

  /{ID}:
    description: Retrieve title by ID
    displayName: Retrieve title by ID
    get:
      responses:
          200:
            body:
              application/json:
                type: any

/query:
  /{ID}:
    description: Query by Salesforce ID 
    displayName: Query by Salesforce ID
    get:
      responses:
          200:
            body:
              application/json:
                type: any

/sim:
  get:
    queryParameters:
      err:
        type: string
    responses:
      200:
        


